apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-azbq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-azbq
    app.kubernetes.io/part-of: ci10t-776-0051-app
  name: devfile-sample-azbq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-azbq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-azbq
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0051-tenant/ci10t-776-0051-app/devfile-sample-azbq@sha256:0456322663fc219970ecfd89c76c49190d1499b662306a9bcf2198d7c1de038c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
